# Generated by Django 2.1.7 on 2019-03-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='timeout',
            field=models.PositiveIntegerField(default=10, help_text='Abort connection after the configured time', verbose_name='Timeout (seconds)'),
        ),
    ]
