import os

if os.name == 'nt':
    socket_error_code = {
        6: 'Specified event object handle is invalid.',
        8: 'Insufficient memory available.',
        87: 'One or more parameters are invalid.',
        995: 'Overlapped operation aborted.',
        996: 'Overlapped I/O event object not in signaled state.',
        997: '',
        10004: 'Interrupted function call.',
        10009: 'File handle is not valid.',
        10013: 'Permission denied.',
        10014: 'Bad address.',
        10022: 'Invalid argument.',
        10024: 'Too many open files.',
        10035: 'Resource temporarily unavailable.',
        10036: 'Operation now in progress.',
        10037: 'Operation already in progress.',
        10038: 'Socket operation on nonsocket.',
        10039: 'Destination address required.',
        10040: 'Message too long.',
        10041: 'Protocol wrong type for socket.',
        10042: 'Bad protocol option.',
        10043: 'Protocol not supported.',
        10044: 'Socket type not supported.',
        10045: 'Operation not supported.',
        10046: 'Protocol family not supported.',
        10047: 'Address family not supported by protocol family.',
        10048: 'Address already in use.',
        10049: 'Cannot assign requested address.',
        10050: 'Network is down.',
        10051: 'Network is unreachable.',
        10052: 'Network dropped connection on reset.',
        10053: 'Software caused connection abort.',
        10054: 'Connection reset by peer.',
        10055: 'No buffer space available.',
        10056: 'Socket is already connected.',
        10057: 'Socket is not connected.',
        10058: 'Cannot send after socket shutdown.',
        10059: 'Too many references.',
        10060: 'Connection timed out.',
        10061: 'Connection refused.',
        10062: 'Cannot translate name.',
        10063: 'Name too long.',
        10064: 'Host is down.',
        10065: 'No route to host.',
        10066: 'Directory not empty.',
        10067: 'Too many processes.',
        10068: 'User quota exceeded.',
        10069: 'Disk quota exceeded.',
        10070: 'Stale file handle reference.',
        10071: 'Item is remote.',
        10091: 'Network subsystem is unavailable.',
        10092: 'Winsock.dll version out of range.',
        10093: 'Successful WSAStartup not yet performed.',
        10101: 'Graceful shutdown in progress.',
        10102: 'No more results.',
        10103: 'Call has been canceled.',
        10104: 'Procedure call table is invalid.',
        10105: 'Service provider is invalid.',
        10106: 'Service provider failed to initialize.',
        10107: 'System call failure.',
        10108: 'Service not found.',
        10109: 'Class type not found.',
        10110: 'No more results.',
        10111: 'Call was canceled.',
        10112: 'Database query was refused.',
        11001: 'Host not found.',
        11002: 'Nonauthoritative host not found.',
        11003: 'This is a nonrecoverable error.',
        11004: 'Valid name, no data record of requested type.',
        11005: 'QoS receivers.',
        11006: 'QoS senders.',
        11007: 'No QoS senders.',
        11008: 'QoS no receivers.',
        11009: 'QoS request confirmed.',
        11010: 'QoS admission error.',
        11011: 'QoS policy failure.',
        11012: 'QoS bad style.',
        11013: 'QoS bad object.',
        11014: 'QoS traffic control error.',
        11015: 'QoS generic error.',
        11016: 'QoS service type error.',
        11017: 'QoS flowspec error.',
        11018: 'Invalid QoS provider buffer.',
        11019: 'Invalid QoS filter style.',
        11020: 'Invalid QoS filter type.',
        11021: 'Incorrect QoS filter count.',
        11022: 'Invalid QoS object length.',
        11023: 'Incorrect QoS flow count.',
        11024: 'Unrecognized QoS object.',
        11025: 'Invalid QoS policy object.',
        11026: 'Invalid QoS flow descriptor.',
        11027: 'Invalid QoS provider-specific flowspec.',
        11028: 'Invalid QoS provider-specific filterspec.',
        11029: 'Invalid QoS shape discard mode object.',
        11030: 'Invalid QoS shaping rate object.',
        11031: 'Reserved policy QoS element type.'
    }
else:
    socket_error_code = {
        0: 'success',
        1: 'operation not permitted',
        2: 'no such file or directory',
        3: 'no such process',
        4: 'interrupted system call',
        5: 'input/output error',
        6: 'no such device or address',
        7: 'argument list too long',
        8: 'exec format error',
        9: 'bad file descriptor',
        10: 'no child processes',
        11: 'resource temporarily unavailable',
        12: 'cannot allocate memory',
        13: 'permission denied',
        14: 'bad address',
        15: 'block device required',
        16: 'device or resource busy',
        17: 'file exists',
        18: 'invalid cross-device link',
        19: 'no such device',
        20: 'not a directory',
        21: 'is a directory',
        22: 'invalid argument',
        23: 'too many open files in system',
        24: 'too many open files',
        25: 'inappropriate ioctl for device',
        26: 'text file busy',
        27: 'file too large',
        28: 'no space left on device',
        29: 'illegal seek',
        30: 'read-only file system',
        31: 'too many links',
        32: 'broken pipe',
        33: 'numerical argument out of domain',
        34: 'numerical result out of range',
        35: 'resource deadlock avoided',
        36: 'file name too long',
        37: 'no locks available',
        38: 'function not implemented',
        39: 'directory not empty',
        40: 'too many levels of symbolic links',
        41: 'unknown error 41',
        42: 'no message of desired type',
        43: 'identifier removed',
        44: 'channel number out of range',
        45: 'level 2 not synchronized',
        46: 'level 3 halted',
        47: 'level 3 reset',
        48: 'link number out of range',
        49: 'protocol driver not attached',
        50: 'no csi structure available',
        51: 'level 2 halted',
        52: 'invalid exchange',
        53: 'invalid request descriptor',
        54: 'exchange full',
        55: 'no anode',
        56: 'invalid request code',
        57: 'invalid slot',
        58: 'unknown error 58',
        59: 'bad font file format',
        60: 'device not a stream',
        61: 'no data available',
        62: 'timer expired',
        63: 'out of streams resources',
        64: 'machine is not on the network',
        65: 'package not installed',
        66: 'object is remote',
        67: 'link has been severed',
        68: 'advertise error',
        69: 'srmount error',
        70: 'communication error on send',
        71: 'protocol error',
        72: 'multihop attempted',
        73: 'rfs specific error',
        74: 'bad message',
        75: 'value too large for defined data type',
        76: 'name not unique on network',
        77: 'file descriptor in bad state',
        78: 'remote address changed',
        79: 'can not access a needed shared library',
        80: 'accessing a corrupted shared library',
        81: '.lib section in a.out corrupted',
        82: 'attempting to link in too many shared libraries',
        83: 'cannot exec a shared library directly',
        84: 'invalid or incomplete multibyte or wide character',
        85: 'interrupted system call should be restarted',
        86: 'streams pipe error',
        87: 'too many users',
        88: 'socket operation on non-socket',
        89: 'destination address required',
        90: 'message too long',
        91: 'protocol wrong type for socket',
        92: 'protocol not available',
        93: 'protocol not supported',
        94: 'socket type not supported',
        95: 'operation not supported',
        96: 'protocol family not supported',
        97: 'address family not supported by protocol',
        98: 'address already in use',
        99: 'cannot assign requested address',
        100: 'network is down',
        101: 'network is unreachable',
        102: 'network dropped connection on reset',
        103: 'software caused connection abort',
        104: 'connection reset by peer',
        105: 'no buffer space available',
        106: 'transport endpoint is already connected',
        107: 'transport endpoint is not connected',
        108: 'cannot send after transport endpoint shutdown',
        109: 'too many references: cannot splice',
        110: 'connection timed out',
        111: 'connection refused',
        112: 'host is down',
        113: 'no route to host',
        114: 'operation already in progress',
        115: 'operation now in progress',
        116: 'stale nfs file handle',
        117: 'structure needs cleaning',
        118: 'not a xenix named type file',
        119: 'no xenix semaphores available',
        120: 'is a named type file',
        121: 'remote i/o error',
        122: 'disk quota exceeded',
        123: 'no medium found',
        124: 'wrong medium type'
    }
