# Generated by Django 2.1.7 on 2019-03-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=256)),
                ('port', models.IntegerField(default=80)),
            ],
            options={
                'verbose_name': 'Monitor target',
                'verbose_name_plural': 'Monitor targets',
            },
        ),
    ]
